### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by carlfranz** [cirelli94/vicook#4]
Wheen I type `vicook`

I have this output
```C:\Users\fcirelli>vicook
=== OGGI ===
C:\Users\fcirelli\AppData\Roaming\nvm\v12.17.0\node_modules\vicook\vicook.js:44
    console.log(capitalizeFirstLetter($("h2.second")[0].firstChild.data))
                                                       ^

TypeError: Cannot read property 'firstChild' of undefined
    at logDate (C:\Users\fcirelli\AppData\Roaming\nvm\v12.17.0\node_modules\vicook\vicook.js:44:56)
    at Request._callback (C:\Users\fcirelli\AppData\Roaming\nvm\v12.17.0\node_modules\vicook\vicook.js:22:9)
    at Request.self.callback (C:\Users\fcirelli\AppData\Roaming\nvm\v12.17.0\node_modules\vicook\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\fcirelli\AppData\Roaming\nvm\v12.17.0\node_modules\vicook\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\fcirelli\AppData\Roaming\nvm\v12.17.0\node_modules\vicook\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
```

**Comment by cirelli94** [comment]
Hi @carlfranz , sadly the resource we used to retrieve data from no longer works!
If you are able to give us a link working, we can release a fix!
FYI, this was the link we used previously: [https://grassobbio.vicookcloud.it/menu/](https://grassobbio.vicookcloud.it/menu/)
